### ISSUE TITLE
Add zhuyin/bopomofo

### ISSUE THREAD

**Issue by JohnAZoidberg** [mathsaey/hanyutils#3]
Would you mind if I added conversion, based on the datastructures that are present already, to and from ZhuYin?

**Comment by mathsaey** [comment]
Contribution are always welcome!

I'm not very familiar with ZhuYin. Is there a one to one mapping to pinyin? If there is, are you planning to add ZhuYin as an alternative output function to Pinyin (like `numbered/1` and `marked/1`)? Or did you have something else in mind?

**Comment by JohnAZoidberg** [comment]
> Is there a one to one mapping to pinyin?

Yes, it's not a trivial one to one character translation because both pinyin and zhuyin have some rules how you can combine the characters/letters. But it's an unambiguous mapping.

> are you planning to add ZhuYin as an alternative output function to Pinyin (like `numbered/1` and `marked/1`)?

Yes, exactly. It doesn't have a numbered variant, so only marked. But the marks aren't even added on top of the letters, just after the syllable.

**Comment by mathsaey** [comment]
Sounds good. If you send a PR I'll be sure to look at it and accept it.

**Comment by JohnAZoidberg** [comment]
Is it okay if I change the internal representation of the `Pinyin` struct to

```elixir
  @enforce_keys [:final]
  defstruct tone: 0, initial: "", final: ""
```

instead of

```elixir
  @enforce_keys [:word]
  defstruct tone: 0, word: ""
```

That makes it much easier to transform Pinyin to Zhuyin. Otherwise I'd have to parse it again.
Since the parser already has that information, it's an easy change to make.
There's only the case that somebody provides the pinyin and wants to output pinyin again, where it would add an additional parse step.

I've got a working implementation with tests - just need to make sure I have a full API.

**Comment by mathsaey** [comment]
That sounds like a reasonable change to me. It can also be a nice for people who want to extract additional information from pinyin representations. 

This remark is not entirely clear to me:

>  There's only the case that somebody provides the pinyin and wants to output pinyin again, where it would add an additional parse step.

It's not clear to me why a parse step is needed here. Is this done to handle cases like uang -> wang? If this is the case, my gut feeling tells me some clever pattern matching in `marked/1` and similar might be able to handle this. Otherwise, it might be worth it to convert the struct to:

```elixir
@enforce_keys [:final, :word]
defstruct tone: 0, initial: "", final: "", word: ""
```

If possible, please submit the pinyin changes and the bopomofo addition as separate pull requests (or as separate commits in a single pull request).

**Comment by JohnAZoidberg** [comment]
> That sounds like a reasonable change to me. It can also be a nice for people who want to extract additional information from pinyin representations.
> 
> This remark is not entirely clear to me:
> 
> > There's only the case that somebody provides the pinyin and wants to output pinyin again, where it would add an additional parse step.
> 
> It's not clear to me why a parse step is needed here. Is this done to handle cases like uang -> wang? If this is the case, my gut feeling tells me some clever pattern matching in `marked/1` and similar might be able to handle this. Otherwise, it might be worth it to convert the struct to:
> 
> ```elixir
> @enforce_keys [:final, :word]
> defstruct tone: 0, initial: "", final: "", word: ""
> ```

See https://github.com/mathsaey/hanyutils/pull/5#discussion_r830089938

> If possible, please submit the pinyin changes and the bopomofo addition as separate pull requests (or as separate commits in a single pull request).

Zhuyin PR here: https://github.com/JohnAZoidberg/hanyutils/pull/1
Since the pinyin split branch is not on your repo, I can't merge into that branch on this repo.

**Comment by JohnAZoidberg** [comment]
Btw, great project and code. It's fun to work with!
